# Generated by Django 5.0.4 on 2024-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_artist_alter_album_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='listened',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
